[package]
name = "referrals-archway"
version = "0.1.0"
edition = "2021"

[lib]
path = "archway.rs"
test = false
doctest = false

[dependencies]
archway-bindings.workspace = true
cosmwasm-std.workspace = true

referrals-cw.workspace = true
