[package]
name = "rewards-pot-cw"
version = "0.1.0"
edition = "2021"

[lib]
path = "rewards-pot-cw.rs"
test = false
doctest = false

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
